index:
    path: /{_locale}
    controller: App\Controller\ViewtubeController::index
    requirements:
        _locale: en|es

indexSinLocale:
    path: /
    controller: App\Controller\ViewtubeController::indexSinLocale

verVideo:
    path: /{_locale}/video/{id}
    controller: App\Controller\ViewtubeController::verVideo
    requirements:
        _locale: en|es
        id: '\d+'

verVideoSinLocale:
    path: /video/{id}
    controller: App\Controller\ViewtubeController::verVideoSinLocale

nuevoVideo:
    path: /{_locale}/video/nueva
    controller: App\Controller\ViewtubeController::nuevoVideo
    requirements:
        _locale: en|es

nuevoVideoSinLocale:
    path: /video/nueva
    controller: App\Controller\ViewtubeController::nuevoVideoSinLocale

videoCreada:
    path: /{_locale}/video/creada
    controller: App\Controller\ViewtubeController::videoCreada
    requirements:
        _locale: en|es

videoCreadaSinLocale:
    path: /video/creada
    controller: App\Controller\ViewtubeController::videoCreadaSinLocale

editarVideo:
    path: /{_locale}/video/editar/{id}
    controller: App\Controller\ViewtubeController::editarVideo
    requirements:
        _locale: en|es

editarVideoSinLocale:
    path: /video/editar/{id}
    controller: App\Controller\ViewtubeController::editarVideoSinLocale

borrarVideo:
    path: /{_locale}/video/borrar/{id}
    controller: App\Controller\ViewtubeController::borrarVideo
    requirements:
        _locale: en|es

borrarVideoSinLocale:
    path: /video/borrar/{id}
    controller: App\Controller\ViewtubeController::borrarVideoSinLocale

verPerfil:
    path: /{_locale}/perfil/{id}
    controller: App\Controller\ViewtubeController::verPerfil
    requirements:
        _locale: en|es
        id: '\d+'

verPerfilSinLocale:
    path: /perfil/{id}
    controller: App\Controller\ViewtubeController::verPerfilSinLocale