index:
    path: /{_locale}
    controller: App\Controller\BlogController::index
    requirements:
        _locale: en|es

indexSinLocale:
    path: /
    controller: App\Controller\BlogController::indexSinLocale

verNoticia:
    path: /{_locale}/noticia/{id}
    controller: App\Controller\BlogController::verNoticia
    requirements:
        _locale: en|es
        id: '\d+'

verNoticiaSinLocale:
    path: /noticia/{id}
    controller: App\Controller\BlogController::verNoticiaSinLocale

nuevaNoticia:
    path: /{_locale}/noticia/nueva
    controller: App\Controller\BlogController::nuevaNoticia
    requirements:
        _locale: en|es

nuevaNoticiaSinLocale:
    path: /noticia/nueva
    controller: App\Controller\BlogController::nuevaNoticiaSinLocale

noticiaCreada:
    path: /{_locale}/noticia/creada
    controller: App\Controller\BlogController::noticiaCreada
    requirements:
        _locale: en|es

noticiaCreadaSinLocale:
    path: /noticia/creada
    controller: App\Controller\BlogController::noticiaCreadaSinLocale

editarNoticia:
    path: /{_locale}/noticia/editar/{id}
    controller: App\Controller\BlogController::editarNoticia
    requirements:
        _locale: en|es

editarNoticiaSinLocale:
    path: /noticia/editar/{id}
    controller: App\Controller\BlogController::editarNoticiaSinLocale

borrarNoticia:
    path: /{_locale}/noticia/borrar/{id}
    controller: App\Controller\BlogController::borrarNoticia
    requirements:
        _locale: en|es

borrarNoticiaSinLocale:
    path: /noticia/borrar/{id}
    controller: App\Controller\BlogController::borrarNoticiaSinLocale
