index:
    path: /{_locale}
    controller: App\Controller\BlogController::index
    requirements:
        _locale: en|es

indexSinLocale:
    path: /
    controller: App\Controller\BlogController::indexSinLocale

verVideo:
    path: /{_locale}/video/{id}
    controller: App\Controller\BlogController::verVideo
    requirements:
        _locale: en|es
        id: '\d+'

verVideoSinLocale:
    path: /video/{id}
    controller: App\Controller\BlogController::verVideoSinLocale

nuevaVideo:
    path: /{_locale}/video/nueva
    controller: App\Controller\BlogController::nuevaVideo
    requirements:
        _locale: en|es

nuevaVideoSinLocale:
    path: /video/nueva
    controller: App\Controller\BlogController::nuevaVideoSinLocale

videoCreada:
    path: /{_locale}/video/creada
    controller: App\Controller\BlogController::videoCreada
    requirements:
        _locale: en|es

videoCreadaSinLocale:
    path: /video/creada
    controller: App\Controller\BlogController::videoCreadaSinLocale

editarVideo:
    path: /{_locale}/video/editar/{id}
    controller: App\Controller\BlogController::editarVideo
    requirements:
        _locale: en|es

editarVideoSinLocale:
    path: /video/editar/{id}
    controller: App\Controller\BlogController::editarVideoSinLocale

borrarVideo:
    path: /{_locale}/video/borrar/{id}
    controller: App\Controller\BlogController::borrarVideo
    requirements:
        _locale: en|es

borrarVideoSinLocale:
    path: /video/borrar/{id}
    controller: App\Controller\BlogController::borrarVideoSinLocale
